_G.ToggleColor = Color3.fromRGB(255,0,0)
_G.ButtonColor = Color3.fromRGB(0,255,0)
_G.SliderColor = Color3.fromRGB(0,0,255)

 

local library = loadstring(game:HttpGet(('https://pastebin.com/raw/FsJak6AT')))() -- It's obfuscated, I won't let you see my ugly coding skills. =)

local GUI = library:CreateWindow("Shi")

local AutoFarm = GUI:CreateFolder("Main")


local Credits = GUI:CreateFolder("Credits")

function toTarget(pos, targetPos, targetCFrame)
    local tween_s = game:GetService"TweenService"
    local info = TweenInfo.new((targetPos - pos).Magnitude/getgenv().speed, Enum.EasingStyle.Linear)
    local tween, err = pcall(function()
        local tween = tween_s:Create(game:GetService("Players").LocalPlayer.Character["HumanoidRootPart"], info, {CFrame = targetCFrame * CFrame.fromAxisAngle(Vector3.new(1,0,0), math.rad(90))})
        tween:Play()
    end)
    if not tween then return err end
end		
Credits:Label("VERY SMALL VERSION",Color3.fromRGB(38,38,38),Color3.fromRGB(0,216,111)) --BgColor,TextColor

Credits:Label("Special For Espense",Color3.fromRGB(38,38,38),Color3.fromRGB(0,216,111)) --BgColor,TextColor
Credits:Label("by SharKK#1954",Color3.fromRGB(38,38,38),Color3.fromRGB(0,216,111)) --BgColor,TextColor
Credits:Label("tinyurl.com/sharkk-roblox",Color3.fromRGB(38,38,38),Color3.fromRGB(0,216,111)) --BgColor,TextColor
Credits:Label("If you have bugs, write to me.",Color3.fromRGB(38,38,38),Color3.fromRGB(0,216,111)) --BgColor,TextColor
Credits:Label("thanks - ily Lya",Color3.fromRGB(38,38,38),Color3.fromRGB(0,216,111)) --BgColor,TextColor

AutoFarm:Toggle("Auto Farm",function(bool)
    shared.toggle = bool
    spawn(function()
        if shared.toggle == true then
            shared.Enabled = true
            shared.Settings = {
                CanGetScroll = true,
                CanRankUp    = false,
                AllowBoss    = false,
                PlayerHeight = -15, -- If u got a free exploit, change this to above -20
                TweenSpeed = 1,
            }
        
            loadstring(game:HttpGet("https://raw.githubusercontent.com/Godne8825/Avakir/Scripts/Shinobi%20Life%202%20%5BV%3A%201.7%5D", true))()
        else
            shared.Enabled = false
            shared.Settings = {
                CanGetScroll = false,
                CanRankUp    = false,
                AllowBoss    = false,
                PlayerHeight = -15, -- If u got a free exploit, change this to above -20
                TweenSpeed = 1,
            }
        
            loadstring(game:HttpGet("https://raw.githubusercontent.com/Godne8825/Avakir/Scripts/Shinobi%20Life%202%20%5BV%3A%201.7%5D", true))() 
        end
    end)
end)

AutoFarm:Toggle("Auto War",function(bool22)
    shared.toggle22 = bool22
    spawn(function()
        while wait() and shared.toggle22 do
				for i,v in pairs(workspace.npc:GetChildren()) do
					if v.ClassName == "Model" and v:FindFirstChild("npc") and string.find(v.Name, "npc") and v:FindFirstChild("HumanoidRootPart") and v:FindFirstChild("Humanoid") and v.Head.CFrame.Y > -1000 and not v:FindFirstChild("megaboss") then
						wait(.1)
                        v.Humanoid.Health = 0
					elseif v.ClassName == "Model" and v:FindFirstChild("npc") and string.find(v.Name, "npc") and v:FindFirstChild("HumanoidRootPart") and v:FindFirstChild("Humanoid") and v.Head.CFrame.Y > -1000 and v:FindFirstChild("megaboss") then
						wait(6)
						pcall(function()
							toTarget(game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.Position,v.HumanoidRootPart.Position,CFrame.new(v.HumanoidRootPart.Position))
							v.Humanoid.Health = 0
						end)
					end
				end
			end
    end)
end)
-- game.Players.LocalPlayer.Backpack.canspin.Value = true

--[[
    -- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local A_1 = "addstat"
local A_2 = "chakra"
local A_3 = 12
local Event = game:GetService("Players").LocalPlayer.startevent
Event:FireServer(A_1, A_2, A_3)

]]

